SELECT ENAME 
FROM EMP 
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SCOTT') 
AND DEPTNO =(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

SELECT * FROM EMP 
WHERE JOB='MANAGER' 
AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');

SELECT ENAME,SAL FROM EMP
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='KING')
AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

SELECT * FROM EMP 
WHERE JOB='SALESMAN' 
AND DEPTNO =(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');

SELECT ENAME,SAL,JOB,HIREDATE 
FROM EMP
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS') 
AND HIREDATE<(SELECT HIREDATE FROM EMP WHERE ENAME='KING');

SELECT * FROM EMP 
WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');

SELECT DNAME FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME LIKE'%A%');

SELECT ENAME FROM EMP WHERE COMM IS NOT NULL;

SELECT LOC FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL AND DEPTNO =40);
