SELECT ENAME,SAL
FROM EMP
WHERE SAL=(SELECT MAX(SAL) FROM EMP);

SELECT ENAME,SAL 
FROM EMP 
WHERE SAL=(SELECT MIN(SAL) FROM EMP);

SELECT ENAME,HIREDATE
FROM EMP
WHERE HIREDATE=(SELECT MIN(HIREDATE)FROM EMP);

SELECT ENAME,HIREDATE 
FROM EMP 
WHERE HIREDATE=(SELECT MAX(HIREDATE) FROM EMP);

SELECT ENAME,COMM
FROM EMP 
WHERE COMM=(SELECT MIN(COMM) FROM EMP);

SELECT ENAME,SAL,COMM
FROM EMP
WHERE COMM=(SELECT MAX(COMM) FROM EMP);

SELECT *FROM EMP
WHERE EMPNO=(SELECT MAX(EMPNO) FROM EMP);

SELECT * FROM EMP
WHERE HIREDATE=(SELECT MAX(HIREDATE) FROM EMP);

SELECT *FROM EMP
WHERE SAL*12=(SELECT MAX(SAL*12) FROM EMP);

SELECT ENAME,SAL*12,JOB
FROM EMP
WHERE SAL*12=(SELECT MAX(SAL*12) FROM EMP WHERE JOB='SALESMAN');
