SELECT E.ENAME,D.LOC FROM EMP E 
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

SELECT D.DNAME,E.SAL,E.ENAME FROM EMP E 
INNER JOIN DEPT D 
ON  E.DEPTNO=D.DEPTNO;

SELECT D.DNAME,E.SAL*12 FROM EMP E 
INNER JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO WHERE SAL>2340;

SELECT E.ENAME,D.DNAME FROM EMP E 
INNER JOIN DEPT D 
ON E.DEPTNO = D.DEPTNO WHERE D.DNAME LIKE '%A%';

SELECT E.ENAME, D.DNAME FROM EMP E  
INNER JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO WHERE JOB='SALESMAN';

SELECT D.DNAME, E.JOB FROM EMP E 
INNER JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO WHERE E. JOB LIKE 'S%' AND D.DNAME LIKE 'S%';

SELECT D.DNAME,E.MGR FROM EMP E 
INNER JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO WHERE MGR='7839';

SELECT D.DNAME,E.HIREDATE FROM EMP E 
INNER JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO WHERE E.HIREDATE>'1983-12-31' AND D.DNAME IN ('ACCOUNTING','RESEARCH');

SELECT E.ENAME,D.DNAME FROM EMP E 
INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO 
WHERE E.COMM IS NOT NULL AND E.DEPTNO IN(10,30);

SELECT D.DNAME,E.EMPNO FROM EMP E 
INNER JOIN DEPT D 
ON E.DEPTNO=D.DEPTNO WHERE E.EMPNO IN(7839,7902) AND D.LOC='NEW YORK';
