SELECT E.ENAME,M.ENAME 
FROM EMP E,EMP M 
WHERE E.MGR=M.EMPNO AND E.JOB='CLERK';

SELECT E.ENAME,M.JOB 
FROM EMP E,EMP M 
WHERE E.MGR=M.EMPNO AND E.DEPTNO IN(10,20);

SELECT E.ENAME, M.ENAME,E.SAL,M.SAL 
FROM EMP E, EMP M
WHERE E.MGR=M.EMPNO 
AND E.SAL>2300
AND M.MGR>2300; 

SELECT E.ENAME,M.ENAME,E.HIREDATE,M.HIREDATE
FROM EMP E, EMP M
WHERE E.MGR=M.EMPNO
AND E.HIREDATE<'1982-01-01';

SELECT E.ENAME,M.ENAME,M.COMM,E.COMM 
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND E.JOB='SALESMAN'
AND M.DEPTNO IN(30);

SELECT E.ENAME,M.ENAME,E.SAL,M.SAL
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND E.SAL>M.SAL;

SELECT E.ENAME,E.HIREDATE,M.ENAME,M.HIREDATE 
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND M.HIREDATE<E.HIREDATE;

SELECT E.ENAME,M.ENAME
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND E.JOB=M.JOB;

SELECT E.ENAME,M.ENAME 
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND M.JOB='MANAGER';

SELECT E.ENAME,M.ENAME,E.SAL*12,M.SAL*12
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND E.DEPTNO IN(10,20) AND M.SAL>E.SAL;

SELECT E.ENAME,M.JOB
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO;

SELECT E.ENAME,M.SAL
FROM EMP E,EMP M
WHERE E.MGR=M.EMPNO
AND MOD(M.SAL,100)=50;
