select *from emp;
select *from emp where job='clerk' AND sal<1500;
select ename,hiredate from emp where job='manager' AND deptno=30;
select sal*12 from emp where job='salesman' AND deptno=30 AND sal*12>14000;
select ename from emp where sal<1100 AND job='clerk';
select ename,sal,sal*12,deptno from emp where deptno=20 AND sal>1100 And sal*12>1200;
select empno ,ename from emp where job='manager' AND deptno=20;
select *from emp where deptno=20 OR deptno=30;
 select *from emp where job='analyst' AND deptno=10;
 select *from emp where job='president' AND sal=4000;
 select ename,deptno,job from emp where job='clerk' and (deptno=10 OR deptno=20);
select *from emp where (job='clerk' OR 'manager') AND deptno=10;
select ename from emp where deptno IN(10,20,30,40);
select *from emp where empno IN (7902,7839);
select *from emp where job IN ('manager','salesman','clerk');
select ename from emp where hiredate >'1981-12-31' AND hiredate<'1987-01-01';
select *from emp where sal>1250 and sal<3000;
select ename from emp where hiredate >81 AND (deptno=10 OR deptno=30);
select ename ,sal*12 from emp where (job='manager' OR 'clerk') AND (deptno=10 OR deptno=30);
select sal*12 from emp where (sal between 1000 AND 4000) AND ( sal*12)>15000;
