SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP
			  WHERE ENAME='SMITH');

SELECT DNAME,LOC 
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP
              WHERE ENAME='KING');
              
SELECT LOC 
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP
              WHERE EMPNO=7902);
              
SELECT DNAME,LOC ,DEPTNO
FROM DEPT 
WHERE DEPTNO IN(SELECT DEPTNO FROM EMP
              WHERE ENAME LIKE '%R');
              
SELECT DNAME
FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP
              WHERE JOB='PRESIDENT');
              
SELECT ENAME FROM EMP
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT
			  WHERE DNAME='ACCOUNTING');
              
SELECT ENAME,SAL
FROM EMP 
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT
              WHERE LOC='CHICAGO');
              
SELECT *FROM EMP 
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT
              WHERE DNAME='SALES');
              
SELECT ENAME,SAL*12
FROM EMP 
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT
              WHERE LOC='NEW YORK');
		
SELECT ENAME FROM EMP
WHERE DEPTNO=(SELECT DEPTNO FROM DEPT
              WHERE DNAME='OPERATIONS');
