SELECT *FROM EMP;
SELECT *FROM DEPT;
SELECT ENAME,SAL*12 FROM EMP;
SELECT ENAME FROM EMP 
WHERE SAL>(SELECT SAL FROM EMP 
           WHERE ENAME='ADAMS');
SELECT ENAME,SAL FROM EMP
WHERE SAL<(SELECT SAL FROM EMP
           WHERE ENAME='KING');
SELECT ENAME,DEPTNO FROM EMP
WHERE DEPTNO=(SELECT DEPTNO FROM EMP
           WHERE ENAME='JONES');
SELECT ENAME,JOB FROM EMP
WHERE JOB=(SELECT JOB FROM EMP
           WHERE ENAME='JAMES');
SELECT EMPNO,ENAME,SAL*12 AS ANNUAL_SAL FROM EMP
WHERE SAL*12>(SELECT SAL*12 FROM EMP
              WHERE ENAME='WARD');
SELECT ENAME,HIREDATE FROM EMP 
WHERE HIREDATE<(SELECT HIREDATE FROM EMP
                WHERE ENAME='SCOTT');
SELECT ENAME,HIREDATE FROM EMP
WHERE HIREDATE>(SELECT HIREDATE FROM EMP
                WHERE JOB='PRESIDENT');
SELECT EMPNO,ENAME,SAL FROM EMP 
WHERE SAL<(SELECT SAL FROM EMP 
		   WHERE EMPNO='7839');
SELECT*FROM EMP
WHERE HIREDATE<(SELECT HIREDATE FROM EMP 
                WHERE ENAME='MILLER');
SELECT ENAME,EMPNO,SAL FROM EMP
WHERE SAL>(SELECT SAL FROM EMP
           WHERE ENAME='ALLEN');
SELECT ENAME,SAL FROM EMP 
WHERE SAL>(SELECT SAL FROM EMP 
           WHERE ENAME='MILLER') AND SAL<(SELECT SAL FROM EMP
                                          WHERE ENAME='ALLEN');
SELECT *FROM EMP 
WHERE DEPTNO=20 AND JOB=(SELECT JOB FROM EMP
                         WHERE ENAME='SMITH');
SELECT *FROM EMP 
WHERE JOB='MANAGER' AND DEPTNO=(SELECT DEPTNO FROM EMP
							  WHERE ENAME='TURNER');
SELECT ENAME,HIREDATE FROM EMP
WHERE HIREDATE>'1980-12-31' AND HIREDATE<(SELECT HIREDATE FROM EMP
                                          WHERE ENAME='KING');
SELECT ENAME,SAL,SAL*12   FROM EMP 
WHERE SAL<(SELECT SAL FROM EMP 
           WHERE ENAME='BLAKE')
           AND SAL>3500;
SELECT *FROM EMP 
WHERE SAL>(SELECT SAL FROM EMP
           WHERE ENAME='SCOTT')AND SAL<(SELECT SAL FROM EMP
                                        WHERE ENAME='KING');
SELECT ENAME,DEPTNO FROM EMP
WHERE ENAME LIKE 'A%' AND DEPTNO=(SELECT DEPTNO FROM EMP
                                  WHERE ENAME='BLAKE');
SELECT ENAME,COMM FROM EMP
WHERE COMM IS NOT NULL AND JOB=(SELECT JOB FROM EMP  
                    WHERE ENAME='SMITH');
SELECT *FROM EMP 
WHERE JOB='CLERK' AND DEPTNO=(SELECT DEPTNO FROM EMP
                              WHERE ENAME='TURNER');
SELECT ENAME,SAL,JOB,SAL*12 FROM EMP
WHERE SAL>(SELECT SAL FROM EMP 
           WHERE ENAME='SMITH') AND SAL<(SELECT SAL FROM EMP
                                         WHERE ENAME='KING');
        
